// apps/web/src/App.tsx
import { useEffect, useState } from "react";

import {
  damagePer100CostToNumber,
  exactToNumber,
  exactToPercent,
  powerResilienceLogRatioView,
  projectCleanSequenceV1,
  type PowerResilienceRelation,
} from "@strainspace/geometry-engine";
import type {
  D6Requirement,
  D6RequirementWire,
} from "@strainspace/rule-schema";

import { analyzeForces } from "./analysis.js";
import { loadFixtureDataset, type FixtureDataset } from "./data.js";

type LoadState =
  | { readonly kind: "loading" }
  | { readonly kind: "error"; readonly message: string }
  | { readonly kind: "ready"; readonly dataset: FixtureDataset };

export interface AppProps {
  readonly loader?: () => Promise<FixtureDataset>;
}

type PairCoordinateView =
  "indexed-difference" | "exact-ratio" | "approximate-log-ratio";

const representationLabels: Record<PairCoordinateView, string> = {
  "indexed-difference": "Indexed difference",
  "exact-ratio": "Exact ratio",
  "approximate-log-ratio": "Approx. log ratio",
};

export function App({ loader = loadFixtureDataset }: AppProps) {
  const [loadState, setLoadState] = useState<LoadState>({ kind: "loading" });
  const [sourceFactionId, setSourceFactionId] = useState("");
  const [targetFactionId, setTargetFactionId] = useState("");
  const [representation, setRepresentation] = useState<PairCoordinateView>(
    "approximate-log-ratio",
  );
  const [counterfactualApplied, setCounterfactualApplied] = useState(false);
  const [selectedSourceId, setSelectedSourceId] = useState("");
  const [selectedTargetId, setSelectedTargetId] = useState("");

  useEffect(() => {
    let active = true;
    loader()
      .then((dataset) => {
        if (active) setLoadState({ kind: "ready", dataset });
      })
      .catch((error: unknown) => {
        if (active)
          setLoadState({
            kind: "error",
            message: error instanceof Error ? error.message : "Unknown error",
          });
      });
    return () => {
      active = false;
    };
  }, [loader]);

  if (loadState.kind === "loading") return <LoadingState />;
  if (loadState.kind === "error")
    return <ErrorState message={loadState.message} />;
  if (loadState.dataset.factions.length < 2) return <EmptyState />;

  const { factions, criterion, counterProfiles, thresholdMap } =
    loadState.dataset;
  const source =
    factions.find((faction) => faction.factionId === sourceFactionId) ??
    factions[0];
  const defaultTarget = factions.find(
    (faction) => faction.factionId !== source?.factionId,
  );
  const requestedTarget = factions.find(
    (faction) => faction.factionId === targetFactionId,
  );
  const target =
    requestedTarget?.factionId === source?.factionId
      ? defaultTarget
      : (requestedTarget ?? defaultTarget);
  if (source === undefined || target === undefined) return <EmptyState />;

  const availableCounter = counterProfiles.find(
    (candidate) => candidate.replaces.factionId === source.factionId,
  );
  const analysis = analyzeForces(
    source,
    target,
    criterion,
    counterfactualApplied ? availableCounter : undefined,
  );
  if (!analysis.ok) return <ErrorState message={analysis.error.message} />;
  const snapshot = analysis.value;
  const fallbackCell = snapshot.matrix.cells.at(-1);
  const selectedCell =
    snapshot.matrix.cells.find(
      (cell) =>
        cell.sourceEntityId === selectedSourceId &&
        cell.targetEntityId === selectedTargetId,
    ) ?? fallbackCell;
  if (selectedCell === undefined) return <EmptyState />;

  const selectedSource = snapshot.source.entities.find(
    (entity) => entity.id === selectedCell.sourceEntityId,
  );
  const selectedTarget = snapshot.target.entities.find(
    (entity) => entity.id === selectedCell.targetEntityId,
  );
  const selectedProfile = selectedSource?.attackProfiles.find(
    (profile) => profile.id === selectedCell.best.sourceProfileId,
  );
  if (
    selectedSource === undefined ||
    selectedTarget === undefined ||
    selectedProfile === undefined
  ) {
    return (
      <ErrorState message="The selected coverage cell could not be resolved." />
    );
  }
  const projected = projectCleanSequenceV1(
    selectedProfile,
    selectedTarget.defense,
  );
  if (!projected.ok) return <ErrorState message={projected.error.message} />;
  const projection = projected.value;
  const coveredCells = snapshot.matrix.cells.filter(
    (cell) => cell.best.covered,
  ).length;
  const coveragePercent = Math.round(
    (coveredCells / snapshot.matrix.cells.length) * 100,
  );
  const activeRegion = thresholdMap.regions.find(
    (region) =>
      region.regionId === projection.powerResilience.relation.regionId,
  );

  function changeSource(nextId: string) {
    const nextTarget = factions.find((faction) => faction.factionId !== nextId);
    setSourceFactionId(nextId);
    setTargetFactionId(nextTarget?.factionId ?? "");
    setCounterfactualApplied(false);
    setSelectedSourceId("");
    setSelectedTargetId("");
  }

  function changeTarget(nextId: string) {
    setTargetFactionId(nextId);
    setCounterfactualApplied(false);
    setSelectedTargetId("");
  }

  return (
    <main className="app-shell">
      <header className="hero">
        <div className="brand-lockup">
          <span className="brand-mark" aria-hidden="true">
            S²
          </span>
          <div>
            <p className="eyebrow">Deterministic force geometry</p>
            <h1>StrainSpace</h1>
          </div>
        </div>
        <p className="hero-thesis">
          Find the response your force <em>doesn’t</em> have—then cross the
          exact boundary that repairs it.
        </p>
        <div className="exact-badge">
          <span className="status-dot" /> Exact D6 enumeration
        </div>
      </header>

      <section className="control-ribbon" aria-label="Analysis controls">
        <label>
          <span>Analyzing force</span>
          <select
            value={source.factionId}
            onChange={(event) => changeSource(event.target.value)}
          >
            {factions.map((faction) => (
              <option key={faction.factionId} value={faction.factionId}>
                {faction.displayName}
              </option>
            ))}
          </select>
        </label>
        <div className="direction-arrow" aria-hidden="true">
          against
        </div>
        <label>
          <span>Opposing force</span>
          <select
            value={target.factionId}
            onChange={(event) => changeTarget(event.target.value)}
          >
            {factions
              .filter((faction) => faction.factionId !== source.factionId)
              .map((faction) => (
                <option key={faction.factionId} value={faction.factionId}>
                  {faction.displayName}
                </option>
              ))}
          </select>
        </label>
        <div className="representation-control">
          <span>Pair coordinate</span>
          <div className="segmented" role="group" aria-label="Pair coordinate">
            {(Object.keys(representationLabels) as PairCoordinateView[]).map(
              (option) => (
                <button
                  key={option}
                  type="button"
                  className={representation === option ? "active" : ""}
                  aria-pressed={representation === option}
                  onClick={() => setRepresentation(option)}
                >
                  {representationLabels[option]}
                </button>
              ),
            )}
          </div>
        </div>
      </section>

      <section className="summary-strip" aria-label="Analysis summary">
        <article>
          <span>Pair coverage</span>
          <strong>{coveragePercent}%</strong>
          <small>
            {coveredCells} of {snapshot.matrix.cells.length} relations meet
            criterion
          </small>
        </article>
        <article className={snapshot.holes.length > 0 ? "warning" : "positive"}>
          <span>Absolute holes</span>
          <strong>{snapshot.holes.length.toString().padStart(2, "0")}</strong>
          <small>
            {snapshot.holes.length > 0
              ? "No adequate response exists"
              : "All target regions covered"}
          </small>
        </article>
        <article>
          <span>Coverage criterion</span>
          <strong>{exactToPercent(criterion.threshold)}</strong>
          <small>
            chance to remove ≥ {criterion.minimumModelsRemoved} model
          </small>
        </article>
        <article>
          <span>Selected coordinate</span>
          <strong>
            {formatRelation(
              projection.powerResilience.relation,
              representation,
            )}
          </strong>
          <small>{activeRegion?.label ?? "Unknown region"}</small>
        </article>
      </section>

      <section className="workspace-grid">
        <article className="panel matrix-panel">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Relational field</p>
              <h2>Pair coverage matrix</h2>
            </div>
            <div className="legend" aria-label="Coverage legend">
              <span>
                <i className="swatch covered" /> Covered
              </span>
              <span>
                <i className="swatch exposed" /> Exposed
              </span>
            </div>
          </div>
          <p className="panel-note">
            Rows act; columns resist. Select a cell to inspect its complete
            projection.
          </p>
          <div className="matrix-scroll">
            <table className="coverage-table">
              <thead>
                <tr>
                  <th scope="col" className="corner-label">
                    source ↓ / target →
                  </th>
                  {snapshot.target.entities.map((entity) => (
                    <th scope="col" key={entity.id}>
                      <span>{entity.displayName}</span>
                      <small>
                        R{entity.defense.resilience} · P
                        {formatRequirement(
                          entity.defense.protectionRequirement,
                        )}
                      </small>
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {snapshot.source.entities.map((sourceEntity) => (
                  <tr key={sourceEntity.id}>
                    <th scope="row">
                      <span>{sourceEntity.displayName}</span>
                      <small>{sourceEntity.cost} resource</small>
                    </th>
                    {snapshot.target.entities.map((targetEntity) => {
                      const cell = snapshot.matrix.cells.find(
                        (candidate) =>
                          candidate.sourceEntityId === sourceEntity.id &&
                          candidate.targetEntityId === targetEntity.id,
                      );
                      if (cell === undefined)
                        return <td key={targetEntity.id}>—</td>;
                      const selected = cell === selectedCell;
                      return (
                        <td key={targetEntity.id}>
                          <button
                            type="button"
                            className={`matrix-cell ${cell.best.covered ? "covered" : "exposed"} ${selected ? "selected" : ""}`}
                            aria-label={`${sourceEntity.displayName} against ${targetEntity.displayName}: ${exactToPercent(cell.best.capability, 1)}`}
                            aria-pressed={selected}
                            onClick={() => {
                              setSelectedSourceId(sourceEntity.id);
                              setSelectedTargetId(targetEntity.id);
                            }}
                          >
                            <strong>
                              {exactToPercent(cell.best.capability, 0)}
                            </strong>
                            <span>
                              {cell.best.covered ? "covered" : "holeward"}
                            </span>
                          </button>
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </article>

        <aside className="panel pair-panel">
          <div className="panel-heading compact">
            <div>
              <p className="eyebrow">Selected relation</p>
              <h2>
                {selectedSource.displayName} <span>→</span>{" "}
                {selectedTarget.displayName}
              </h2>
            </div>
            <span
              className={`coverage-pill ${selectedCell.best.covered ? "covered" : "exposed"}`}
            >
              {selectedCell.best.covered ? "Covered" : "Exposed"}
            </span>
          </div>
          <p className="profile-name">
            Best profile · {selectedProfile.displayName}
          </p>
          <div className="scalar-pair">
            <div>
              <span>Power</span>
              <strong>{selectedProfile.power}</strong>
            </div>
            <div className="strain-link">
              <span>{representationLabels[representation]}</span>
              <strong>
                {formatRelation(
                  projection.powerResilience.relation,
                  representation,
                )}
              </strong>
            </div>
            <div>
              <span>Resilience</span>
              <strong>{selectedTarget.defense.resilience}</strong>
            </div>
          </div>
          <dl className="stage-list">
            <div>
              <dt>Accuracy</dt>
              <dd>
                {formatRequirement(selectedProfile.accuracyRequirement)} ·{" "}
                {exactToPercent(projection.accuracy.probability, 1)}
              </dd>
            </div>
            <div>
              <dt>Power / resilience</dt>
              <dd>
                {formatRequirement(
                  projection.powerResilience.relation.requirement,
                )}{" "}
                ·{" "}
                {exactToPercent(
                  projection.powerResilience.outcomeEvent.probability,
                  1,
                )}
              </dd>
            </div>
            <div>
              <dt>Failed protection</dt>
              <dd>
                {formatRequirement(
                  projection.penetrationProtection.effectiveRequirement,
                )}{" "}
                save ·{" "}
                {exactToPercent(
                  projection.penetrationProtection.failedProtectionProbability,
                  1,
                )}
              </dd>
            </div>
            <div>
              <dt>Effect per attack</dt>
              <dd>
                {exactToPercent(projection.singleAttackEffectProbability, 1)}
              </dd>
            </div>
            <div>
              <dt>Efficiency</dt>
              <dd>
                {damagePer100CostToNumber(
                  selectedCell.best.damagePerCost,
                ).toFixed(2)}{" "}
                dmg / 100
              </dd>
            </div>
          </dl>
        </aside>
      </section>

      <section className="projection-grid">
        <article className="panel threshold-panel">
          <div className="panel-heading compact">
            <div>
              <p className="eyebrow">Piecewise map</p>
              <h2>Threshold region</h2>
            </div>
            <strong className="large-threshold">
              {formatRequirement(
                projection.powerResilience.relation.requirement,
              )}
            </strong>
          </div>
          <div className="threshold-track">
            {thresholdMap.regions.toReversed().map((region) => (
              <div
                key={region.regionId}
                className={
                  region.regionId === activeRegion?.regionId ? "active" : ""
                }
              >
                <span>{formatRequirement(region.requirement)}</span>
                <small>{region.label}</small>
              </div>
            ))}
          </div>
          <p className="math-note">
            Boundary lines are defined by the ratio P/R. The selected pair sits
            in <strong>{activeRegion?.label.toLowerCase()}</strong> territory;
            values inside this region share one D6 projection.
          </p>
        </article>

        <article className="panel dice-panel">
          <div className="panel-heading compact">
            <div>
              <p className="eyebrow">Finite sample space Ω</p>
              <h2>Six-outcome dice space</h2>
            </div>
            <span className="fraction">
              {projection.powerResilience.outcomeEvent.probability.numerator}/
              {projection.powerResilience.outcomeEvent.probability.denominator}
            </span>
          </div>
          <div
            className="dice-row"
            aria-label="Power-resilience successful D6 faces"
          >
            {projection.powerResilience.outcomeEvent.faces.map((face) => {
              const success =
                projection.powerResilience.outcomeEvent.successfulFaces.includes(
                  face,
                );
              return (
                <div key={face} className={success ? "success" : "failure"}>
                  <span>{face}</span>
                  <small>{success ? "success" : "miss"}</small>
                </div>
              );
            })}
          </div>
          <p className="math-note">
            Every face is enumerated once. No model-generated arithmetic enters
            this result.
          </p>
        </article>

        <article className="panel distribution-panel">
          <div className="panel-heading compact">
            <div>
              <p className="eyebrow">Projected effect</p>
              <h2>Removal distribution</h2>
            </div>
            <span className="fraction">
              E {projection.effectDistribution.expectedModelsRemoved.numerator}/
              {projection.effectDistribution.expectedModelsRemoved.denominator}
            </span>
          </div>
          <div className="distribution-bars">
            {projection.effectDistribution.outcomes.map((outcome) => (
              <div key={outcome.damagingHits}>
                <span>{outcome.modelsRemoved} removed</span>
                <i>
                  <b
                    style={{
                      width: `${Math.max(2, exactToNumber(outcome.probability) * 100)}%`,
                    }}
                  />
                </i>
                <strong>{exactToPercent(outcome.probability, 1)}</strong>
              </div>
            ))}
          </div>
        </article>
      </section>

      <section className="hole-section">
        <div className="hole-copy">
          <p className="eyebrow">Structural diagnosis</p>
          <h2>
            {snapshot.holes.length > 0
              ? "A response region is missing."
              : "The seeded response gap is closed."}
          </h2>
          <p>
            {snapshot.holes.length > 0
              ? "No profile crosses the declared reliability boundary for the target region below. Aggregate strength alone would not isolate this absence."
              : "The counter-profile crosses both the pair threshold and removal-probability boundary. Coverage is recomputed from the same exact operators."}
          </p>
          {availableCounter !== undefined && (
            <button
              type="button"
              className={`counterfactual-button ${counterfactualApplied ? "active" : ""}`}
              onClick={() => setCounterfactualApplied((current) => !current)}
            >
              <span>
                {counterfactualApplied
                  ? "Restore baseline"
                  : "Apply counterfactual"}
              </span>
              <strong>
                {counterfactualApplied
                  ? "Anchor Shear"
                  : availableCounter.profile.displayName}
              </strong>
              <i aria-hidden="true">→</i>
            </button>
          )}
        </div>
        <div className="hole-list" aria-live="polite">
          {snapshot.holes.length === 0 ? (
            <div className="closed-hole">
              <span aria-hidden="true">✓</span>
              <div>
                <strong>Absolute hole closed</strong>
                <small>
                  Every target region now has at least one adequate response.
                </small>
              </div>
            </div>
          ) : (
            snapshot.holes.map((hole) => {
              const entity = snapshot.target.entities.find(
                (candidate) => candidate.id === hole.targetEntityIds[0],
              );
              return (
                <article key={hole.holeId}>
                  <div>
                    <span className="hole-index">
                      H{snapshot.holes.indexOf(hole) + 1}
                    </span>
                    <strong>
                      {entity?.displayName ?? hole.targetRegionId}
                    </strong>
                  </div>
                  <dl>
                    <div>
                      <dt>Region</dt>
                      <dd>
                        R{entity?.defense.resilience} · P
                        {entity === undefined
                          ? "?"
                          : formatRequirement(
                              entity.defense.protectionRequirement,
                            )}{" "}
                        · H{entity?.defense.health}
                      </dd>
                    </div>
                    <div>
                      <dt>Gap to criterion</dt>
                      <dd>{exactToPercent(hole.capabilityGap, 1)}</dd>
                    </div>
                    <div>
                      <dt>Best available</dt>
                      <dd>{hole.bestAvailableResponse}</dd>
                    </div>
                  </dl>
                </article>
              );
            })
          )}
        </div>
      </section>

      <footer>
        <span>STRNSPC / deterministic vertical slice</span>
        <span>Finite spaces · explicit assumptions · original proxy data</span>
      </footer>
    </main>
  );
}

function formatRelation(
  relation: PowerResilienceRelation,
  representation: PairCoordinateView,
): string {
  if (representation === "exact-ratio")
    return `${relation.exactRatio.numerator}/${relation.exactRatio.denominator}`;
  if (representation === "indexed-difference")
    return `${relation.indexedDifference >= 0 ? "+" : ""}${relation.indexedDifference}`;
  const approximate = powerResilienceLogRatioView(relation).value;
  return `≈${approximate >= 0 ? "+" : ""}${approximate.toFixed(2)}`;
}

function formatRequirement(
  requirement: D6Requirement | D6RequirementWire,
): string {
  if (typeof requirement === "object")
    return requirement.kind === "impossible"
      ? "Impossible"
      : `${requirement.minimumSuccessfulFace}+`;
  return requirement === "impossible" ? "Impossible" : `${requirement}+`;
}

function LoadingState() {
  return (
    <main className="state-shell" aria-busy="true">
      <div className="state-mark">S²</div>
      <p className="eyebrow">Constructing finite spaces</p>
      <h1>Loading exact fixture geometry…</h1>
      <div className="loading-line">
        <span />
      </div>
    </main>
  );
}

function EmptyState() {
  return (
    <main className="state-shell">
      <div className="state-mark">∅</div>
      <p className="eyebrow">No relation to project</p>
      <h1>Load at least two validated force fixtures.</h1>
      <p>The analysis surface needs one acting force and one opposing force.</p>
    </main>
  );
}

function ErrorState({ message }: { readonly message: string }) {
  return (
    <main className="state-shell error" role="alert">
      <div className="state-mark">!</div>
      <p className="eyebrow">Validation stopped safely</p>
      <h1>The force geometry could not be constructed.</h1>
      <p>{message}</p>
    </main>
  );
}

// apps/web/src/lib/App.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import "../styles.css";

  import {
    exactToPercent,
    projectCleanSequenceV1,
  } from "@strainspace/geometry-engine";
  import type {
    CounterProfileFixtureV1,
    ProxyFactionV1,
  } from "@strainspace/rule-schema";

  import { analyzeForces, type AnalysisSnapshot } from "../analysis.js";
  import { loadFixtureDataset, type FixtureDataset } from "../data.js";
  import {
    buildSceneModel,
    representationLabels,
    type PairCoordinateView,
    type SceneModel,
  } from "../presentation.js";
  import StrainSpaceScene from "./StrainSpaceScene.svelte";

  type LoadState =
    | { readonly kind: "loading" }
    | { readonly kind: "error"; readonly message: string }
    | { readonly kind: "ready"; readonly dataset: FixtureDataset };

  type ResolvedView =
    | { readonly kind: "empty" }
    | { readonly kind: "error"; readonly message: string }
    | {
        readonly kind: "ready";
        readonly dataset: FixtureDataset;
        readonly source: ProxyFactionV1;
        readonly target: ProxyFactionV1;
        readonly counter?: CounterProfileFixtureV1;
        readonly snapshot: AnalysisSnapshot;
        readonly model: SceneModel;
      };

  interface Props {
    readonly loader?: () => Promise<FixtureDataset>;
    readonly renderScene?: boolean;
  }

  let { loader = loadFixtureDataset, renderScene = true }: Props = $props();
  let loadState = $state<LoadState>({ kind: "loading" });
  let sourceFactionId = $state("");
  let targetFactionId = $state("");
  let representation = $state<PairCoordinateView>("approximate-log-ratio");
  let counterfactualApplied = $state(false);
  let selectedSourceId = $state("");
  let selectedTargetId = $state("");

  onMount(() => {
    let active = true;
    void loader()
      .then((dataset) => {
        if (active) loadState = { kind: "ready", dataset };
      })
      .catch((error: unknown) => {
        if (active)
          loadState = {
            kind: "error",
            message: error instanceof Error ? error.message : "Unknown error",
          };
      });
    return () => {
      active = false;
    };
  });

  const resolved = $derived.by<ResolvedView | undefined>(() => {
    if (loadState.kind !== "ready") return undefined;
    const dataset = loadState.dataset;
    if (dataset.factions.length < 2) return { kind: "empty" };
    const source =
      dataset.factions.find(
        (faction) => faction.factionId === sourceFactionId,
      ) ?? dataset.factions[0];
    const defaultTarget = dataset.factions.find(
      (faction) => faction.factionId !== source?.factionId,
    );
    const requestedTarget = dataset.factions.find(
      (faction) => faction.factionId === targetFactionId,
    );
    const target =
      requestedTarget?.factionId === source?.factionId
        ? defaultTarget
        : (requestedTarget ?? defaultTarget);
    if (source === undefined || target === undefined) return { kind: "empty" };

    const counter = dataset.counterProfiles.find(
      (candidate) => candidate.replaces.factionId === source.factionId,
    );
    const analysis = analyzeForces(
      source,
      target,
      dataset.criterion,
      counterfactualApplied ? counter : undefined,
    );
    if (!analysis.ok) return { kind: "error", message: analysis.error.message };
    const snapshot = analysis.value;
    const selectedCell =
      snapshot.matrix.cells.find(
        (cell) =>
          cell.sourceEntityId === selectedSourceId &&
          cell.targetEntityId === selectedTargetId,
      ) ?? snapshot.matrix.cells.at(-1);
    if (selectedCell === undefined) return { kind: "empty" };
    const selectedSource = snapshot.source.entities.find(
      (entity) => entity.id === selectedCell.sourceEntityId,
    );
    const selectedTarget = snapshot.target.entities.find(
      (entity) => entity.id === selectedCell.targetEntityId,
    );
    const selectedProfile = selectedSource?.attackProfiles.find(
      (profile) => profile.id === selectedCell.best.sourceProfileId,
    );
    if (
      selectedSource === undefined ||
      selectedTarget === undefined ||
      selectedProfile === undefined
    )
      return {
        kind: "error",
        message: "The selected coverage cell could not be resolved.",
      };
    const projection = projectCleanSequenceV1(
      selectedProfile,
      selectedTarget.defense,
    );
    if (!projection.ok)
      return { kind: "error", message: projection.error.message };

    return {
      kind: "ready",
      dataset,
      source,
      target,
      ...(counter === undefined ? {} : { counter }),
      snapshot,
      model: buildSceneModel(
        snapshot,
        selectedSource,
        selectedTarget,
        selectedProfile,
        projection.value,
        dataset.thresholdMap,
        representation,
        counterfactualApplied,
      ),
    };
  });

  function changeSource(nextId: string) {
    if (loadState.kind !== "ready") return;
    const nextTarget = loadState.dataset.factions.find(
      (faction) => faction.factionId !== nextId,
    );
    sourceFactionId = nextId;
    targetFactionId = nextTarget?.factionId ?? "";
    counterfactualApplied = false;
    selectedSourceId = "";
    selectedTargetId = "";
  }

  function changeTarget(nextId: string) {
    targetFactionId = nextId;
    counterfactualApplied = false;
    selectedTargetId = "";
  }

  function selectCell(sourceId: string, targetId: string) {
    selectedSourceId = sourceId;
    selectedTargetId = targetId;
  }
</script>

{#if loadState.kind === "loading"}
  <main class="state-shell" aria-busy="true">
    <div class="state-mark">S²</div>
    <p class="eyebrow">Constructing finite spaces</p>
    <h1>Loading exact fixture geometry…</h1>
    <div class="loading-line"><span></span></div>
  </main>
{:else if loadState.kind === "error"}
  <main class="state-shell error" role="alert">
    <div class="state-mark">!</div>
    <p class="eyebrow">Validation stopped safely</p>
    <h1>The force geometry could not be constructed.</h1>
    <p>{loadState.message}</p>
  </main>
{:else if resolved?.kind === "empty"}
  <main class="state-shell">
    <div class="state-mark">∅</div>
    <p class="eyebrow">No relation to project</p>
    <h1>Load at least two validated force fixtures.</h1>
    <p>The analysis surface needs one acting force and one opposing force.</p>
  </main>
{:else if resolved?.kind === "error"}
  <main class="state-shell error" role="alert">
    <div class="state-mark">!</div>
    <p class="eyebrow">Projection stopped safely</p>
    <h1>The force geometry could not be constructed.</h1>
    <p>{resolved.message}</p>
  </main>
{:else if resolved?.kind === "ready"}
  <main class="app-shell">
    <header class="hud brand-hud">
      <div class="brand-mark" aria-hidden="true">S²</div>
      <div>
        <p class="eyebrow">Deterministic force geometry</p>
        <h1>StrainSpace</h1>
      </div>
      <div class="exact-badge"><i></i> Exact D6 enumeration</div>
    </header>

    <section class="hud control-hud" aria-label="Analysis controls">
      <label>
        <span>Analyzing force</span>
        <select
          value={resolved.source.factionId}
          onchange={(event) => changeSource(event.currentTarget.value)}
        >
          {#each resolved.dataset.factions as faction (faction.factionId)}
            <option value={faction.factionId}>{faction.displayName}</option>
          {/each}
        </select>
      </label>
      <span class="against">against</span>
      <label>
        <span>Opposing force</span>
        <select
          value={resolved.target.factionId}
          onchange={(event) => changeTarget(event.currentTarget.value)}
        >
          {#each resolved.dataset.factions.filter((faction) => faction.factionId !== resolved.source.factionId) as faction (faction.factionId)}
            <option value={faction.factionId}>{faction.displayName}</option>
          {/each}
        </select>
      </label>
      <fieldset>
        <legend>Pair coordinate</legend>
        {#each Object.entries(representationLabels) as [value, label] (value)}
          <button
            type="button"
            class:active={representation === value}
            aria-pressed={representation === value}
            onclick={() => (representation = value as PairCoordinateView)}
            >{label}</button
          >
        {/each}
      </fieldset>
    </section>

    <section class="hud summary-hud" aria-label="Analysis summary">
      <div>
        <span>Coverage</span>
        <strong>{resolved.model.coveragePercent}%</strong>
        <small
          >{resolved.model.coveredCells}/{resolved.model.totalCells} pairs</small
        >
      </div>
      <div class:warning={resolved.model.holes.length > 0}>
        <span>Absolute holes</span>
        <strong
          >{resolved.model.holes.length.toString().padStart(2, "0")}</strong
        >
        <small
          >{resolved.model.holes.length > 0
            ? "response absent"
            : "field closed"}</small
        >
      </div>
      <div>
        <span>Criterion</span>
        <strong>{exactToPercent(resolved.dataset.criterion.threshold)}</strong>
        <small>removal event</small>
      </div>
    </section>

    {#if renderScene}
      <StrainSpaceScene model={resolved.model} onSelect={selectCell} />
    {:else}
      <div class="scene-placeholder" aria-hidden="true"></div>
    {/if}

    <section class="hud selected-hud" aria-live="polite">
      <p class="eyebrow">Selected relation</p>
      <h2>
        {resolved.model.selected.sourceLabel} <span>→</span>
        {resolved.model.selected.targetLabel}
      </h2>
      <p>
        {resolved.model.selected.profileLabel} · {resolved.model.selected
          .regionLabel}
      </p>
      <dl>
        <div>
          <dt>Coordinate</dt>
          <dd>{resolved.model.selected.coordinate}</dd>
        </div>
        <div>
          <dt>Requirement</dt>
          <dd>{resolved.model.selected.requirement}</dd>
        </div>
        <div>
          <dt>Effect</dt>
          <dd>{resolved.model.selected.effect}</dd>
        </div>
      </dl>
    </section>

    <section class="hud counterfactual-hud" aria-live="polite">
      <p class="eyebrow">Structural diagnosis</p>
      <h2>
        {resolved.model.holes.length > 0
          ? "A response region is missing."
          : "The seeded response gap is closed."}
      </h2>
      {#if resolved.model.holes.length > 0}
        {#each resolved.model.holes as hole (hole.id)}
          <p class="hole-line">{hole.targetLabel} · {hole.gap} gap</p>
        {/each}
      {:else}
        <p class="closed-line">Absolute hole closed</p>
      {/if}
      {#if resolved.counter !== undefined}
        <button
          type="button"
          class:active={counterfactualApplied}
          onclick={() => (counterfactualApplied = !counterfactualApplied)}
        >
          <span
            >{counterfactualApplied
              ? "Restore baseline"
              : "Apply counterfactual"}</span
          >
          <strong
            >{counterfactualApplied
              ? "Anchor Shear"
              : resolved.counter.profile.displayName}</strong
          >
        </button>
      {/if}
    </section>

    <p class="interaction-hint">
      Drag to orbit · scroll to zoom · select a matrix tower
    </p>

    <section class="sr-only" aria-label="Accessible coverage data">
      <h2>Pair coverage matrix</h2>
      <table>
        <caption>Exact pair coverage results</caption>
        <thead>
          <tr
            ><th>Source</th><th>Target</th><th>Capability</th><th>Status</th
            ></tr
          >
        </thead>
        <tbody>
          {#each resolved.model.cells as cell (`${cell.sourceEntityId}:${cell.targetEntityId}`)}
            <tr>
              <td>{cell.sourceLabel}</td><td>{cell.targetLabel}</td>
              <td>{cell.capabilityLabel}</td><td
                >{cell.covered ? "Covered" : "Exposed"}</td
              >
            </tr>
          {/each}
        </tbody>
      </table>
    </section>
  </main>
{/if}
